spring.config.import=optional:file:.env[.properties]
spring.application.name=springboot-docker-demo
server.port=8080

#spring.datasource.url=${SPRING_DATABASE_URL}
#spring.datasource.username=${SPRING_DATABASE_USERNAME}
#spring.datasource.password=${SPRING_DATABASE_PASSWORD}

spring.datasource.url=jdbc:postgresql://localhost:5432/testservice
spring.datasource.username=user
spring.datasource.password=mypassword