name: Master and Releaser

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testservice
          POSTGRES_USER: user
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
    steps:
      # Step 1 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 - Setting up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3 - Create settings.xml for GitHub Packages
      - name: Set up settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      # Step 3 - Build the application
      - name: Build the application
        env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/testservice"
          SPRING_DATASOURCE_USERNAME: "user"
          SPRING_DATASOURCE_PASSWORD: "mypassword"
        run: mvn clean package

      # Step 4 - Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5 - Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Use the GitHub actor (the user triggering the action)
          password: ${{ secrets.GITHUB_TOKEN }} # Use the provided GitHub token

      # Step 6 - Build and Push Container (Versioned with sha)
      - name: Build and Push Container (Versioned with sha)
        run: |
          IMAGE_NAME="ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):${{ github.sha }}"
          echo "Building versioned image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Step 7 - Build and Push Container (Latest)
      - name: Build and Push Container (Latest)
        run: |
          IMAGE_NAME="ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):latest"
          echo "Building latest image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
