name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Checkout code
      - uses: actions/checkout@v3

      # Step 2 - Setting up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3 - Running formatting check (like Prettier)
      - name: Check Code Formatting with Spotless
        run: mvn spotless:check

      # Step 4 - Running static code analysis (like ESLint)
      - name: Run Static Code Analysis with Checkstyle
        run: mvn checkstyle:check

      # Step 5 - Running tests
      - name: Run Tests
        run: mvn test

      # Step 6 - Running build (only if everything else succeeds)
      - name: Run Build
        run: mvn clean package
